const questions = [
    {
        question: "What are the key elements of the Source-Filter Model?",
        answers: ["Vocal folds, vocal tract, speech ", " Diaphragm, lungs, tongue", " Breath, canal, air", "Vibrations, filtering, modulation", "None of these answers apply "],
        correct: [0]
    },
    {
        question: "Differences between the Spectrogram and the Power Spectrum. Which statements are TRUE?",
        answers: ["They represent the same quantities but use different scales", "The Power Spectrum does not show the time evolution, while the Spectrogram shows only the time evolution of the Signal's total absolute value", "The Spectrogram is an extension of the Power Spectrum where the frequency content of the signal's power is portrayed for a series of consecutive time points", "The power spectrum can be considered as a “slice” of the spectrogram at a specific time instant", "The Spectrogram represents the oscillations of the signal just like the Power Spectrum, but it colors them according to their intensity", "None of these answers apply"],
        correct: [2,3]
    },
  {
    question: "What is a tone burst? ",
    answers: [
      "A sinusoid whose amplitude is weighted by a specific time window",
      "A sinusoid at high intensity with a varying frequency",
      "A Gaussian stimulus at high intensity and varying duration",
      "A mix of sinusoids able to elicit different portions of the basilar membrane",
      "None of these answers apply"
    ],
    correct: [0]
  },
  {
    question: "What is the difference between Discrete Time Signals and Digital Signals? ",
    answers: [
      "Discrete Time signals are continuous in time while Digital Signals are discrete in time",
      "Discrete Time signals are continuous in amplitude while Digital Signals are discrete in amplitude",
      "Discrete Time signals are continuous in amplitude while Digital Signals are continuous in time",
      "They are the same",
      "Both are discrete in time and in amplitude"
    ],
    correct: [1]
  },
  {
    question: "Which of the following sentences about Psychophysics are TRUE? ",
    answers: [
      "In a DETECTION test we ask “which is the value among N possibilities?”",
      "In a MEASURING test we ask “what is the symbol's semantic value?”",
      "In a SCALING test we ask “can you sense the stimulus?”",
      "In a COMPREHENSION test we ask “what is the symbol's semantic value?”",
      "In a DISCRIMINATION test we ask “can you distinguish two different stimuli?”",
      "In a RECOGNITION test we ask “what is the corresponding symbol among N possibilities?”"
    ],
    correct: [3,4,5]
  },
  {
    question: "Which of these lists present in correct order different classes of Auditory Evoked Potentials from highest to lowest latency? ",
    answers: [
      "Late potentials, Auditory Brainstem Response, Electrocochleography",
      "Late potentials, Auditory Brainstem Response, Middle latency response",
      "Late potentials, Middle latency response, Auditory Brainstem Response",
      "Late potentials, Electrocochleography, Auditory Brainstem Response",
      "None of these answers apply"
    ],
    correct: [0,2]
  },
  {
    question: "Which of these statements about distortion product otoacoustic emissions (DPOAE) are TRUE? ",
    answers: [
      "DPOAE are generated in the outer ear",
      "DPOAE are generated by cochlear nonlinearities as a result of interference of two pure tones",
      "DPOAE are distortions with frequency at linear combinations of the original tones",
      "The presence of DPOAE does not depend on hearing level at all",
      "DPOAE amplitude is almost independent of hearing level when higher than 20 dB",
      "None of these answers apply"
    ],
    correct: [1,2,4]
  },
  {
    question: "What are the main stimuli used in visual evoked potential? ",
    answers: [
      "Clicks",
      "Pulses",
      "Flashes",
      "Coherent Light",
      "Pattern reversal",
      "None of these"
    ],
    correct: [2,4]
  },
  {
    question: "Which of these statements are FALSE in Ultrasound imaging?",
    answers: [
      "An increase of the frequency of the ultrasound beam results in an increase in resolution of the final image",
      "An increase in wavelength of the ultrasound beam gives an increase in resolution of the resulting image",
      "An increase in penetration of the ultrasound beam can be achieved by increasing ultrasound wavelength",
      "Small structures like the eye are explored with high ultrasound frequencies",
      "Both resolution and penetration requirements can be met by independently changing frequency and wavelength of the Ultrasound",
      "Wavelength is directly proportional to frequency",
      "None of the statements above are false"
    ],
    correct: [1,4,5]
  },
          {
            question: "Which is the assumption of Fourier Analysis that makes Spectrogram better suited for time varying signals than simple Power Spectrum?",
            answers: [
              "Stationarity",
              "Aliasing",
              "Multiple Sources",
              "Duality",
              "Linearity"
            ],
            correct: [0]
          },
          {
            question: "What is the expression of the Stevens power Law?",
            answers: [
              "I=α S",
              "S=kS^a",
              "I/s=k",
              "SI=k α",
              "None of the above"
            ],
            correct: [4]
          },
          {
            question: "What is the reference point between the MEL and PHON scales?",
            answers: [
              "1kHz",
              "100Hz",
              "The Hearing Threshold",
              "The scales represent different information and cannot be linked",
              "100 MELs 40 PHON at 100Hz"
            ],
            correct: [0]
          },
          {
            question: "What is the point of reference linking the MEL and PHON scales?",
            answers: [
              "The Hearing Threshold",
              "The scales represent different information and cannot be linked",
              "1kHz",
              "100Hz",
              "100 MELs 40 PHON at 100Hz"
            ],
            correct: [2]
          },
          {
            question: "Which of these signals may represent a tone burst?",
            answers: [
              "A Sinusoid whose amplitude is modulated by a specific window",
              "A Sinusoid at high intensity with a small time duration",
              "Gaussian stimulus at high intensity and small duration",
              "A mix of sinusoids able to elicit different portions of the basilar membrane",
              "All of the above"
            ],
            correct: [0]
          },
          {
            question: "A masker sound [at 500 Hz]:",
            answers: [
              "is more effective if its frequency is low rather than high",
              "at 250 Hz has no effect in masking a sound at 250 Hz",
              "will never increase the threshold of audibility of a masked sound",
              "at 250 Hz will mask a higher range of frequencies with respect to a masker at 1000 Hz"
            ],
            correct: [0, 3]
          },
          {
            question: "Which of these is true about Beating generated by two close tones at f1 and f2 (f2>f1)?",
            answers: [
              "It results in a periodic signal modulated by a sinusoid of frequency |f2-f1|",
              "If f1=1000 Hz and f2=1005 Hz, the resulting sensation is a 5 Hz modulated 1000 Hz tone",
              "The frequency of the beat is |f2-f1|",
              "It is the result of two positive interferences in a row followed by one negative interference in each period"
            ],
            correct: [0, 1]
          },
          {
            question: "Which of these is true about the speech processing strategies in cochlear implants?",
            answers: [
              "The CIS strategy is the most complex and consuming",
              "The total number of electrodes activated is variable in the SPEAK strategy",
              "The total number of electrodes activated is variable in the N-of-M strategy",
              "A fixed number of electrodes is activated in the CIS and N-of-M strategies"
            ],
            correct: [1, 3]
          },
          {
            question: "Which among these are clinical signs most relevant to diagnose a healthy retina?",
            answers: [
              "Adhesion to the inner eye wall",
              "Changes in size of the macula",
              "Absence of ruptures",
              "Color of the pupil",
              "Size of the ganglion layer",
              "Vascularisation of all parts around the macula",
              "Normal vascularization of all parts around the macula",
              "Absence of abnormal proliferation of new vessels"
            ],
            correct: [0, 2, 5]
          },
          {
            question: "Which among these are clinical signs most relevant to diagnose a compromised retina?",
            answers: [
              "Adhesion to the inner eye wall",
              "Changes in size of the macula",
              "Presence of ruptures",
              "Absence of ruptures",
              "Change in color of the retina",
              "Size of the ganglion layer",
              "Abnormal vascularization around the macula",
              "Normal vascularization",
              "Absence of abnormal proliferation of new vessels"
            ],
            correct: [0, 1, 2]
          }, 

  {
    question: "What are the advantages of the Spectrogram with respect to the Power Spectrum?",
    answers: [
      "They represent the same quantities but use different scales",
      "The Power Spectrum does not show the time evolution, while the Spectrogram shows only the time evolution of the signal's total absolute value",
      "The Spectrogram is an extension of the Power Spectrum where the frequency content of the signal is exploited for different time instants",
      "The Spectrogram represents the oscillations of the signal just like the Power Spectrum, but it colors them according to their intensity",
      "The Power Spectrum can represent a slice of the Spectrogram for a specific time instant"
    ],
    correct: [2, 4]
  },
  {
    question: "Which of these statements are TRUE in Ultrasound imaging? (3 points)",
    answers: [
      "Both resolution and penetration requirements can be met by independently changing frequency and wavelength of the Ultrasound",
      "An increase of the frequency of the ultrasound beam results in an increase in resolution of the final image",
      "An increase in wavelength of the ultrasound beam gives an increase in resolution of the resulting image",
      "An increase in penetration of the ultrasound beam can be achieved by decreasing ultrasound wavelength",
      "Small structures like the eye are explored with high ultrasound frequencies"
    ],
    correct: [1]
  },
  {
    question: "Which of the following are limitations for cortical visual implants? (3 points)",
    answers: [
      "The connections of the interface are too slow",
      "The convergence has already taken place within the hypercolumn structure",
      "The retinotopy is not well defined",
      "It is hard to extract information relevant to orientation of borders",
      "The cortical area is too small",
      "The resolution is limited"
    ],
    correct: [1, 3, 5]
  },
  {
    question: "What are the main characteristics of Red, green, and Blue light retinal imaging? (Choose the TRUE statements)",
    answers: [
      "Green light 540-575 nm enhances the choroid structure",
      "Red light 630-640 nm enhances the choroid structure",
      "Green light 540-575 nm enhances the fibres converging to the optic disk",
      "Blue light 490 nm has a mid penetration and enhances the vessels",
      "Use of blue light 490 nm enhances the surface layers of retina"
    ],
   correct: [1, 4]
  },
  {
    question: "Which of these statements about Otoacoustic Emissions (OAEs) are TRUE? (3 points)",
    answers: [
      "OAEs are used in several clinical applications",
      "OAEs are low level sounds generated by the cochlea",
      "OAEs are a subjective indicator of the cochlear anatomic/functional integrity in vivo",
      "OAEs have no intra-subject test-retest repeatability",
      "OAEs are generated by the active mechanisms mediated by Outer Hair Cells",
      "OAEs can only be measured after a specific age"
    ],
   correct: [0, 1, 4]
  },
  {
    question: "Which of these statements about Otoacoustic Emissions (OAEs) are FALSE?",
    answers: [
      "OAEs are a subjective indicator of the cochlear anatomic/functional integrity in vivo",
      "OAEs can only be measured after a specific age",
      "OAEs have no intra-subject test-retest repeatability"
    ],
    correct: [0, 1, 2]
  },
  {
    question: "Which of these statements about evoked potentials are FALSE?",
    answers: [
      "Near-Field Potentials can be recorded directly on the surface of a nerve",
      "Auditory Brainstem Responses (ABR) are Near-Field Potentials",
      "Far-Field Potentials are often measured intraoperatively to monitor the state of the subject",
      "Near-Field Potentials have relatively small amplitudes",
      "Afferent auditory pathways generate sound-evoked electrical potentials",
      "Far-Field Potentials represent the neural activity in more than one structure"
    ],
   correct: [1, 2, 3]
  },
  {
    question: "What are the main elements of a hearing device general schema?",
    answers: [
      "Sound waves, Mechano-Electrical Transducer, Sampling/Quantization, Processing, Electro-Mechanical Transducer, Mechanical Vibrations",
      "Sound waves, Mechano-Electrical Transducer, Sampling/Quantization, Processing, Electro-Mechanical Transducer, Electric Stimuli",
      "Transducer, Processing, Stimulation",
      "Sound waves, microphone, AD converter, Signal Processing, Electrical Stimulation",
      "None of these answers"
    ],
    correct: [0, 1]
  },
  {
    question: "What are the main variables that relate to PITCH?",
    answers: [
      "Linearity",
      "Frequency",
      "Perception",
      "Duration",
      "Rhythmicity",
      "Intensity",
      "Latency"
    ],
    correct: [1, 3, 5]
  },
  {
    question: "Which of these statements about Amplification in Hearing Aids are TRUE? (3 points)",
    answers: [
      "A nonlinear amplification is generally used to amplify high volume sounds",
      "The gain is linear or nonlinear as a function of the input sound level",
      "A linear hearing aid amplifies soft and loud sounds with different gains",
      "It is divided into a Filtering and a true amplification Gain",
      "Loudness as a function of input intensity is the same in sensorineural hearing loss with respect to normal ears",
      "Its function is to boost the level of the electrical signal that is delivered to the hearing aid's loudspeaker"
    ],
    correct: [1, 3, 5]
  },

  {
    question: "Which of the following sentences about Psychophysics are TRUE? (3 points)",
    answers: [
      "In a DISCRIMINATION test we ask: can you distinguish two different stimuli?",
      "In a DETECTION test we ask: which is the value among N possibilities?",
      "In a RECOGNITION test we ask: what is the symbol's semantic value?",
      "In a MEASURING test we ask: what is the corresponding symbol among N possibilities?",
      "In a COMPREHENSION test we ask: can you sense the stimulus?",
      "In a SCALING test we ask: is one stimulus higher/louder than a second one?"
    ],
    correct: [0, 5]
  },
  {
    question: "Which of the following sentences about Psychophysics are true?",
    answers: [
      "Psychophysics is the discipline aimed at studying sensation in response to stimuli",
      "Psychophysics tests have subjective nature because they require the collaboration and active participation and response of the subject under examination and they depend on his/her behavior and/or judgement and several other elements",
      "Psychophysics tests are experiments aimed at achieving the most objective assessment possible, given the subjective nature of the target phenomenon"
    ],
    correct: [0, 1, 2]
  },
  {
    question: "Which of these statements about cochlear stimulation are TRUE? (2 points)",
    answers: [
      "Monopolar electric stimulation of Cochlear Implants is wider but stronger than Bipolar",
      "Monopolar and Bipolar Stimulations have the same shape but different circuits",
      "Bipolar electric stimulation of Cochlear Implants is narrower and stronger than Monopolar",
      "Bipolar electric stimulation of Cochlear Implants stimulates a more specific region of the basilar membrane with respect to Monopolar"
    ],
    correct: [0, 2, 3]
  },
  {
    question: "Sound Pressure Level is:",
    answers: [
      "A measure of Loudness",
      "A perceptual variable",
      "An objective measure",
      "Measured in phons"
    ],
    correct: [2]
  },
  {
    question: "What are the main similarities/differences between the Electroretinogram (ERG) and the Electrooculogram (EOG)?",
    answers: [
      "They are the same",
      "They are both evoked potentials",
      "The EOG is not an evoked potential and it reflects eye-ball movement",
      "The ERG is not an evoked potential",
      "They both measure difference",
      "The ERG is used to detect"
    ],
   correct: [2]
  },
  {
    question: "What are the key elements of the Source-Filter Model?",
    answers: [
      "Vocal folds, vocal tract, speech",
      "Vocal sounds, lips, voice",
      "Breathing, canals, airflow",
      "Vibrations, filtering, modulation",
      "None of these answers"
    ],
    correct: [0]
  },
  {
    question: "Choose one definition to fill the gap: OAEs of newborns and children have ... amplitudes than in adults over the entire frequency region.",
    answers: [
      "Greater",
      "Lower",
      "Same",
      "More spread",
      "More defined"
    ],
    correct: [0]
  },
  {
    question: "What is an audiogram?",
    answers: [
      "An audiogram is a graph that shows the minimum audible threshold for standardized frequencies (pure tones at 200, 400, etc.) as measured by an audiometer",
      "An audiogram gives a measure of the difference between the absolute threshold of the subject and a normal mean threshold conventionally defined by international agreements",
      "It is a HL indicator: increase in dB compared with a reference threshold value (0 dB HL)"
    ],
    correct: [0, 1]
  },
  {
    question: "Which structures are bypassed by using BAHA devices?",
    answers: [
      "Outer Ear and Middle Ear",
      "Outer Ear",
      "Up to the Cochlea (excluded)",
      "They directly stimulate the Brain"
    ],
    correct: [0, 2]
  },
  {
    question: "Choose one definition to fill the gap: With an average latency of ....... the Electroretinogram presents an A-wave and a B-wave of opposite sign.",
    answers: [
      "1 second",
      "2 milliseconds",
      "20 milliseconds",
      "100 milliseconds"
    ],
    correct: [1]
  },

  {
    question: "What is an audiogram?",
    answers: [
      "An audiogram is a graph that shows the minimum audible threshold for standardized frequencies (pure tones at 200, 400, etc.) as measured by an audiometer",
      "An audiogram gives a measure of the difference between the absolute threshold of the subject and a normal mean threshold conventionally defined by international agreements",
      "It is a HL indicator: increase in dB compared with a reference threshold value (0 dB HL)"
    ],
    correct: [0, 1]
  },
  {
    question: "Which structures are bypassed by using BAHA devices?",
    answers: [
      "Outer Ear and Middle Ear",
      "Outer Ear",
      "Up to the Cochlea (excluded)",
      "They directly stimulate the Brain"
    ],
    correct: [0, 2]
  },
  {
    question: "Choose one definition to fill the gap: With an average latency of ....... the Electroretinogram presents an A-wave and a B-wave of opposite sign.",
    answers: [
      "1 second",
      "2 milliseconds",
      "20 milliseconds",
      "100 milliseconds"
    ],
    correct: [1]
  },
  {
    question: "Which of these elements and functions are considered in a Kurzweil's Reading Machine?",
    answers: [
      "A set of electrodes",
      "A central processing unit",
      "A beam splitter",
      "A sound processor",
      "A pattern recognition program"
    ],
    correct: [1, 3, 4]
  }
   // Aggiungi altre domande...
];

let availableIndices = [];
let usedIndices = new Set();
let currentQuestion = {};
let correctCount = 0;
let wrongCount = 0;  
let totalCount = 0;

function resetQuiz() {
    availableIndices = Array.from({length: questions.length}, (_, i) => i);
    usedIndices.clear();
    correctCount = 0;
    wrongCount = 0;
    totalCount = 0;  
    updateScoreDisplay();

}

function randomQuestion() {
    if (availableIndices.length === 0) {
        resultEl.textContent = 'Quiz completato! Ricarica per ricominciare.';
        submitBtn.disabled = true;
        newQBtn.disabled = true;
        return;
    }
    const randIdx = Math.floor(Math.random() * availableIndices.length);
    const questionIdx = availableIndices.splice(randIdx, 1)[0];
    usedIndices.add(questionIdx);
    currentQuestion = questions[questionIdx];
}

const quizContainer = document.getElementById('quiz-container');
const questionEl = document.getElementById('question');
const answersEl = document.getElementById('answers');
const submitBtn = document.getElementById('submit');
const resultEl = document.getElementById('result');
const newQBtn = document.getElementById('new-question');
const scoreEl = document.getElementById('score'); 

resetQuiz();
randomQuestion();
showQuestion();

function shuffleArray(array) {
    const shuffled = [...array];  // Copia per non modificare originale
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function updateScoreDisplay() {
    scoreEl.textContent = `Corrette: ${correctCount} | Errori: ${wrongCount} | Fatte: ${totalCount} /40`;
    totalCount++;  
}

function showQuestion() {
    questionEl.textContent = currentQuestion.question;
    answersEl.innerHTML = '';
    
    const answerList = currentQuestion.answers.map((answer, idx) => ({text: answer, originalIdx: idx}));
    const shuffledList = shuffleArray(answerList);  // Randomizza
    
    shuffledList.forEach(({text, originalIdx}) => {
        const label = document.createElement('label');
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.value = originalIdx;  
        checkbox.dataset.originalIdx = originalIdx; 
        label.appendChild(checkbox);
        label.appendChild(document.createTextNode(` ${text}`));
        answersEl.appendChild(label);
    });
}

submitBtn.addEventListener('click', () => {
    const selected = Array.from(answersEl.querySelectorAll('input:checked')).map(cb => parseInt(cb.value));
    const correctIdx = currentQuestion.correct;
    const isCorrect = selected.length === correctIdx.length && 
                      selected.every(s => correctIdx.includes(s)) && 
                      correctIdx.every(c => selected.includes(c));
    
    if (isCorrect) {
        correctCount++;
    } else {
        wrongCount++;
    }
    updateScoreDisplay();  // Aggiorna counter
    
    resultEl.textContent = isCorrect ? 'Corretto!' : 'Sbagliato! Corrette: ' + correctIdx.map(i => currentQuestion.answers[i]).join(', ');
    resultEl.style.color = isCorrect ? 'green' : 'red';
});

newQBtn.addEventListener('click', () => {
    randomQuestion();
    showQuestion();
    resultEl.textContent = '';
});

document.getElementById('reset').addEventListener('click', () => {
    resetQuiz();
    randomQuestion();
    showQuestion();
    resultEl.textContent = '';
    submitBtn.disabled = false;
    newQBtn.disabled = false;
});
